apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: ClusterIP
  selector:
    app: query         # deployment label for query service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004